### ISSUE TITLE
Sprint 3: Create a Story

### ISSUE THREAD

**Issue by leoliudeprecated** [codepath-project-stories/timeline#81]
http://i.imgur.com/Ru57rgc.png
the text color on Create a Story is kinda hard to read

**Comment by Marusya82** [comment]
I will look into this and play around to see if it makes the visual better

**Comment by dbautist** [comment]
Perhaps we can create a standard button style so that it can be consistently used throughout the app? This is the current style for the "POST" button from the detail view. See https://github.com/codepath-project-stories/timeline/blob/dev/app/src/main/res/drawable/primary_dark_button.xml

![image](https://cloud.githubusercontent.com/assets/3712632/18256487/e24b7848-736a-11e6-9dfb-f2381680f3e0.png)

**Comment by Marusya82** [comment]
PR #89

**Comment by leoliudeprecated** [comment]
ya, i forgot the button in the dialog. it should be the same style.
